CREATE TABLE IF NOT EXISTS ad_launches (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  strategy_id BIGINT UNSIGNED NOT NULL,
  platform ENUM('meta', 'google') NOT NULL,
  connection_id BIGINT UNSIGNED NOT NULL,
  status ENUM('draft', 'created', 'published', 'cancelled') NOT NULL DEFAULT 'draft',
  creative JSON NOT NULL,
  settings JSON NOT NULL,
  external_campaign_id VARCHAR(40) NULL,
  error VARCHAR(400) NULL,
  model VARCHAR(120) NULL,
  created_by BIGINT UNSIGNED NULL,
  launched_by BIGINT UNSIGNED NULL,
  published_by BIGINT UNSIGNED NULL,
  launched_at DATETIME NULL,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_launch_org (organization_id, status),
  CONSTRAINT fk_launch_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_launch_strategy FOREIGN KEY (strategy_id) REFERENCES ad_strategies(id) ON DELETE CASCADE,
  CONSTRAINT fk_launch_conn FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE
) ENGINE=InnoDB;
